setwd("G:\\Economics of security")
iot = read.csv("iot_preprocessed.csv",header = T,strip.white = T)
iot$scandate <- as.Date(iot$scandate)
attach(attacks)
attacks <- iot %>% group_by(scandate) %>% mutate(count = n_distinct(host)) %>% select(scandate,count)
plot(x = scandate, y = count, main="Botnet size", xlab="date ", ylab="infected hosts", pch=19)

honeypot <- readLines("cmds_sequence_2016-07-01.csv")
honeypot <- gsub(pattern = "$$",replacement = "€",x = honeypot,fixed = T)
flieconn <- file("hp_preprocessed.csv")
writeLines(honeypot,flieconn)
honeypot <- read.table("hp_preprocessed.csv",sep = "€",strip.white = T)

honeypots <- read.csv("hp_preprocessed.csv",sep="€",strip.white = T,header = F)
library(plyr)
shells <- count(honeypots$V7)
honeypots$V1 <- as.POSIXct(honeypots$V1,format="%Y-%m-%d %H:%M:%OS")
summary(shells)
head(subset(shells,shells$freq==1),n = 100)
install.packages("dplyr")
library(dplyr)
honeypots %>% group_by(honeypots$"V6") %>% filter(n()>2)
sample_frac() 
ff <- table(honeypots$V6)
ff <- as.data.frame(ff)
head(ff$Freq==1,20)
head(subset(ff,ff$Freq==1,"Var1"),20)