#!/bin/bash
#frequency analysis of each password pair on a daily basis
mkdir results
for i in *.csv; 
do 
cat $i | grep -o -E "\['[^,]{0,15}', '[^,]{0,15}" | sort | uniq -c | sort -n > results/$(echo $i | grep -o -E "[0-9]{2}-[0-9]{2}\." | tr -d ".,");
done



#!/bin/bash
mkdir filtered

echo > "filtered/all"
for i in 0*; 
do 
echo "$i[" >> "filtered/$i"
awk '$1 > 10 { print }' $i  | sort -n -r | tr -d "]'\,," >> filtered/all
echo "$i[" >> "filtered/$i"
#awk -F "[" '$1 > 10 { print $2 "[" $1 }' $i   | sort | tr -d "]'\,," > "filtered/$i" ;
tr -d "]'\,," < $i | awk -F "[" '$1 > 2000{sums[$2]+=$1} END{for (i in sums) print i, "[" sums[i]}'  |  sort -o "filtered/$i" ;
done

awk -F "[" '{sums[$2]+=$1} END{for (i in sums) print sums[i], i }' filtered/all | sort -n -r > filtered/all_f

#create table to import in google sheets

s=$(cat filtered/07-01)
for i in $(ls  -I 07-01 filtered/0*); do
 s=$(echo "$s" |  join  - "$i" -t "[" -a 1 -a 2 -e 0 -o auto  );
done;
echo "$s" > filtered/table
